FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Production

FROM node:20-alpine AS production

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=build /app/src/configs/prisma.config.ts ./prisma.config.ts
COPY --from=build /app/src/configs/prisma ./prisma

RUN ./node_modules/.bin/prisma generate

COPY --from=build /app/dist ./dist

EXPOSE 3000
CMD ["sh", "-c", "./node_modules/.bin/prisma migrate deploy && node dist/server.js"]